id: I85199579
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:49:52+00:00'
last_modified: '2022-06-07T18:41:28.453487+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2191
  title: དར་ལྕེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51E3:
      image_group_id: I3CN2193
      title: ''
      total_pages: 58
      order: 1
      base_file: 51E3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
