id: P003257
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:50:47.097799
source_metadata:
  id: bdr:W3CN2191
  title: དར་ལྕེ།
  author: ''
  volumes:
    f56787f14e6f442fb24ee9d9695b157b:
      image_group_id: I3CN2193
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
